///
/// JHybridNitroVtoViewStateUpdater.cpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © 2026 Marc Rousavy @ Margelo
///

#include "JHybridNitroVtoViewStateUpdater.hpp"
#include "views/HybridNitroVtoViewComponent.hpp"
#include <NitroModules/NitroDefines.hpp>
#include <memory>

namespace margelo::nitro::nitrovto::views {

using namespace facebook;
using ConcreteStateData = react::ConcreteState<HybridNitroVtoViewState>;

void JHybridNitroVtoViewStateUpdater::updateViewProps(jni::alias_ref<jni::JClass> /* class */,
                                           jni::alias_ref<JHybridNitroVtoViewSpec::JavaPart> javaView,
                                           jni::alias_ref<JStateWrapper::javaobject> stateWrapperInterface) {
  std::shared_ptr<JHybridNitroVtoViewSpec> view = javaView->getJHybridNitroVtoViewSpec();

  // Get concrete StateWrapperImpl from passed StateWrapper interface object
  jobject rawStateWrapper = stateWrapperInterface.get();
  if (!stateWrapperInterface->isInstanceOf(react::StateWrapperImpl::javaClassStatic())) {
      throw std::runtime_error("StateWrapper is not a StateWrapperImpl");
  }
  auto stateWrapper = jni::alias_ref<react::StateWrapperImpl::javaobject>{
            static_cast<react::StateWrapperImpl::javaobject>(rawStateWrapper)};

  std::shared_ptr<const react::State> state = stateWrapper->cthis()->getState();
  auto concreteState = std::dynamic_pointer_cast<const ConcreteStateData>(state);
  const HybridNitroVtoViewState& data = concreteState->getData();
  const std::optional<HybridNitroVtoViewProps>& maybeProps = data.getProps();
  if (!maybeProps.has_value()) {
    // Props aren't set yet!
    throw std::runtime_error("HybridNitroVtoViewState's data doesn't contain any props!");
  }
  const HybridNitroVtoViewProps& props = maybeProps.value();
  if (props.modelUrl.isDirty) {
    view->setModelUrl(props.modelUrl.value);
  }
  if (props.isActive.isDirty) {
    view->setIsActive(props.isActive.value);
  }
  if (props.onModelLoaded.isDirty) {
    view->setOnModelLoaded(props.onModelLoaded.value);
  }
  if (props.onFaceTracked.isDirty) {
    view->setOnFaceTracked(props.onFaceTracked.value);
  }
  if (props.onArUnavailable.isDirty) {
    view->setOnArUnavailable(props.onArUnavailable.value);
  }
  if (props.onGlassesDisplayed.isDirty) {
    view->setOnGlassesDisplayed(props.onGlassesDisplayed.value);
  }
  if (props.forwardOffset.isDirty) {
    view->setForwardOffset(props.forwardOffset.value);
  }
  if (props.debug.isDirty) {
    view->setDebug(props.debug.value);
  }
  if (props.showNativeFPS.isDirty) {
    view->setShowNativeFPS(props.showNativeFPS.value);
  }
  if (props.mode.isDirty) {
    view->setMode(props.mode.value);
  }
  if (props.previewBackgroundColor.isDirty) {
    view->setPreviewBackgroundColor(props.previewBackgroundColor.value);
  }
  if (props.isClipOn.isDirty) {
    view->setIsClipOn(props.isClipOn.value);
  }

  // Update hybridRef if it changed
  if (props.hybridRef.isDirty) {
    const auto& maybeFunc = props.hybridRef.value;
    if (maybeFunc.has_value()) {
      maybeFunc.value()(view);
    }
  }
}

} // namespace margelo::nitro::nitrovto::views
