///
/// NitroVtoOnLoad.cpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © 2026 Marc Rousavy @ Margelo
///

#ifndef BUILDING_NITROVTO_WITH_GENERATED_CMAKE_PROJECT
#error NitroVtoOnLoad.cpp is not being built with the autogenerated CMakeLists.txt project. Is a different CMakeLists.txt building this?
#endif

#include "NitroVtoOnLoad.hpp"

#include <jni.h>
#include <fbjni/fbjni.h>
#include <NitroModules/HybridObjectRegistry.hpp>

#include "JHybridNitroVtoViewSpec.hpp"
#include "JFunc_void_std__string.hpp"
#include "JFunc_void.hpp"
#include "views/JHybridNitroVtoViewStateUpdater.hpp"

namespace margelo::nitro::nitrovto {

int initialize(JavaVM* vm) {
  using namespace margelo::nitro;
  using namespace margelo::nitro::nitrovto;
  using namespace facebook;

  return facebook::jni::initialize(vm, [] {
    // Register native JNI methods for nitro-modules >= 0.32
    margelo::nitro::nitrovto::JHybridNitroVtoViewSpec::CxxPart::registerNatives();
    margelo::nitro::nitrovto::JFunc_void_std__string_cxx::registerNatives();
    margelo::nitro::nitrovto::JFunc_void_cxx::registerNatives();
    margelo::nitro::nitrovto::views::JHybridNitroVtoViewStateUpdater::registerNatives();
  });
}

} // namespace margelo::nitro::nitrovto
